%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MRiLab auto generated file: DO NOT EDIT!     %
% Generated by MRiLab "DoWriteXML2m" Generator %
% MRiLab Version 1.3                           %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function dB0=Mag_GaussianHead
%====================================
p.DeltaX=0.08;
p.DeltaY=0.08;
p.DeltaZ=0.08;
p.PosX=0;
p.PosY=0;
p.PosZ=0;
p.Scale=5e-6;
dB0t=MagGaussian(p);
dB0=dB0t;
p=[];
%--------------------
end
