%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MRiLab auto generated file: DO NOT EDIT!     %
% Generated by MRiLab "DoWriteXML2m" Generator %
% MRiLab Version 1.3                           %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function dB0=Mag_LinearHead
%====================================
p.GradX=0;
p.GradY=1;
p.GradZ=0;
p.Scale=6e-5;
dB0t=MagLinear(p);
dB0=dB0t;
p=[];
%--------------------
end
